### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Heyian** [Heyian/github-actions-usage#1]
Implementation

- [ ] Export to CSV/JSON, see [blemke1971 fork](https://github.com/blemke1971/github-actions-usage)
- [ ] Fix typos, see [blemke1971 fork](https://github.com/blemke1971/github-actions-usage)
- [ ] Export to Prometheus Node Exporter Text file collector
- [ ] Add multiple threshold for remaining minutes
